#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const failures = [];
function read(file) { const absolute = path.join(root, file); if (!fs.existsSync(absolute)) { failures.push('Arquivo ausente: ' + file); return ''; } return fs.readFileSync(absolute, 'utf8'); }
function requireText(file, value, expected) { if (!value.includes(expected)) failures.push(file + ' precisa conter: ' + expected); }
const analyst = read('.github/agents/analista.agent.md');
const analysis = read('.github/skills/consignado-analise/SKILL.md');
const context = read('.github/skills/consignado-contexto/SKILL.md');
const base = read('.github/skills/consignado-base/SKILL.md');
const mapTemplate = read('docs/mapas/_template.md');
const contextTemplate = read('docs/contextos/_template.md');
const analysisRoundGate = read('scripts/validateAnalysisRound.js');
const analystOperation = read('docs/operacao-analista.md');
const analystStateCore = read('scripts/validateAnalystStateCore.js');
const analystRenderer = read('scripts/renderAnalystStatus.js');
const kora = read('.github/agents/kora.agent.md');
const koraSkill = read('.github/skills/consignado-kora/SKILL.md');
const koraRound = read('scripts/validateKoraRound.js');
['referencias cruas', 'aprovacao humana explicita', 'Rascunhos e previews'].forEach((expected) => requireText('.github/agents/analista.agent.md', analyst, expected));
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'reutilizacoes previstas');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'collectPrototypeReactions.js');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'collectReferenceStructure.js');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'em cada Section');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'resolvido.json');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'validateAnalysisRound.js --round <rodada> --stage pre-coleta');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'validateAnalysisRound.js --round <rodada> --stage pre-proposta');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'contrato de retorno');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'reencontro');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'As skills deste projeto vivem em `.github/skills/`');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'skill://index.json');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, '.designops/runs/<outra-rodada>/');
requireText('.github/agents/analista.agent.md', analyst, 'pelo leitor local do projeto');
requireText('.github/agents/analista.agent.md', analyst, 'Nao liste diretorios inteiros por padrao');
requireText('.github/agents/analista.agent.md', analyst, 'Em coleta tecnica\nisolada ou laboratorio');
requireText('.github/agents/analista.agent.md', analyst, 'somente `consignado-analise` e\n`figma-plugin-api`');
requireText('.github/agents/analista.agent.md', analyst, 'Em analise completa, carregue');
requireText('.github/agents/analista.agent.md', analyst, 'Em contexto guiado que inclui leitura de\nreferencias Figma');
requireText('.github/agents/analista.agent.md', analyst, '`consignado-contexto`,\n`consignado-analise` e `figma-plugin-api`');
requireText('.github/agents/analista.agent.md', analyst, '`FATO OBSERVADO`, `REGRA\nDOCUMENTADA`, `REGRA CONFIRMADA` ou `[CONFIRMAR]`');
requireText('.github/agents/analista.agent.md', analyst, 'inclusive\nem chamada subsequente de leitura');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, '## Escopo de skills');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'coleta tecnica isolada ou laboratorio');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'somente esta\nskill `consignado-analise`, `figma-plugin-api`');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'Em analise completa, leia tambem');
requireText('.github/skills/consignado-contexto/SKILL.md', context, 'So entao crie ou atualize');
requireText('.github/skills/consignado-contexto/SKILL.md', context, 'ACAO_NO_APP');
requireText('.github/skills/consignado-contexto/SKILL.md', context, '## Contexto guiado com referencias Figma');
requireText('.github/skills/consignado-contexto/SKILL.md', context, '`consignado-contexto`, `consignado-analise` e `figma-plugin-api`');
requireText('.github/skills/consignado-contexto/SKILL.md', context, '`FATO OBSERVADO`, `REGRA\nDOCUMENTADA`, `REGRA CONFIRMADA` ou `[CONFIRMAR]`');
requireText('.github/skills/consignado-contexto/SKILL.md', context, 'Nao liste diretorios inteiros');
requireText('.github/skills/consignado-contexto/SKILL.md', context, 'contexto.json');
requireText('.github/skills/consignado-contexto/SKILL.md', context, 'validateContextDraftCore.js');
requireText('.github/skills/consignado-contexto/SKILL.md', context, 'regra documentada nao e perguntada de novo');
requireText('.github/skills/consignado-contexto/SKILL.md', context, 'nao altere manual global, modalidade');
requireText('.github/skills/consignado-base/SKILL.md', base, 'sem Figma');
requireText('.github/skills/consignado-base/SKILL.md', base, 'aprovacao humana explicita');
requireText('.github/skills/consignado-base/SKILL.md', base, 'merge manual');
requireText('.github/agents/analista.agent.md', analyst, 'contexto-rodada.schema.json');
requireText('.github/agents/analista.agent.md', analyst, 'validateContextDraftCore.js');
requireText('.github/agents/analista.agent.md', analyst, 'validateAnalysisRound.js');
requireText('.github/agents/analista.agent.md', analyst, 'estado-analista.json');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'Figma`, `Sections` e `Contexto curto');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'resumo-operador.md');
requireText('.github/skills/consignado-analise/SKILL.md', analysis, 'O que a base ja\nestabelece');
requireText('docs/operacao-analista.md', analystOperation, 'O que a pessoa operadora fornece');
requireText('docs/operacao-analista.md', analystOperation, 'o que a base ja estabelece');
requireText('scripts/validateAnalystStateCore.js', analystStateCore, 'AGUARDANDO_DECISAO_DO_DESIGNER');
requireText('scripts/renderAnalystStatus.js', analystRenderer, 'Só preciso da sua decisão nestes pontos');
requireText('docs/mapas/_template.md', mapTemplate, 'Origem da regra');
requireText('docs/mapas/_template.md', mapTemplate, 'Composicoes internas');
requireText('docs/contextos/_template.md', contextTemplate, 'Regras locais por etapa');
['pre-coleta', 'pre-proposta', 'artefatos de rodada fora de .designops/runs/<rodada>/', 'PRONTA_PARA_APROVACAO_HUMANA', 'mensagemHumana'].forEach((expected) => requireText('scripts/validateAnalysisRound.js', analysisRoundGate, expected));
requireText('.github/agents/kora.agent.md', kora, 'validateKoraRound.js');
requireText('.github/agents/kora.agent.md', kora, 'diagnoseKoraFailure.js');
requireText('.github/skills/consignado-kora/SKILL.md', koraSkill, 'INCIDENTE_DA_OPERACAO');
requireText('.github/skills/consignado-kora/SKILL.md', koraSkill, 'validateAnalysisRound.js');
requireText('scripts/validateKoraRound.js', koraRound, "'pre-proposta'");
if (failures.length) { console.error('Portoes da analise reprovados:'); failures.forEach((failure) => console.error('- ' + failure)); process.exit(1); }
console.log('Portoes da analise aprovados.');
